context:
  name: roctracer
  version: "7.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/rocm-systems/releases/download/rocm-${{ version }}/roctracer.tar.gz"
    sha256: 95668dccaf649335939b26670c0adb7ee909edee7272a8cd5ce913c562d96e8f
    patches:
      - disable_tests.patch
      - disable_werror.patch
      - skip_anon_struct_codegen.patch

build:
  number: 0
  skip: 
    - not linux
    - hip_compiler_version in (None, "None")

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - libgcc-devel_linux-64 >=15.2.0
    - ${{ compiler('hip') }}
    - cppheaderparser
    - cmake
    - pkg-config
    - ninja
  host:
    - rocm-core ${{ version }}.*
    # Workaround, this should not be needed but roctracer's CMake has some problems
    - hip-clang_linux-64
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}


tests:
  - package_contents:
      include:
        - roctracer/roctracer.h
      lib:
        - roctracer64
        - roctx64
about:
  homepage: https://rocm.docs.amd.com/projects/roctracer
  repository: https://github.com/ROCm/rocm-systems
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "AMD ROCTRACER library"

extra:
  recipe-maintainers:
    - traversaro
