schema_version: 1

context:
  name: rocfft
  version: "7.2.4"

recipe:
  name: rocfft-split
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/rocm-libraries/releases/download/rocm-${{ version }}/rocfft.tar.gz"
    sha256: c37e25e7a4f09a1064c53b93b14c14cb7400f046405ea0ef3ea1f4b4a80d7528

build:
  number: 0
  skip: 
    - not linux
    - hip_compiler_version in (None, "None")

outputs:
  - staging:
      name: rocfft-build
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('hip') }}
        - cmake
        - pkg-config
        - ninja
      host:
        - rocm-core ${{ version }}.*
        - rocm-cmake
        - sqlite
    build:
      script: build.sh

  - package:
      name: librocfft
    inherit:
      from: rocfft-build
      run_exports: false
    build:
      files:
        - bin/**
        - lib/librocfft.so*
        - lib/rocfft/**
        - share/doc/**
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('hip') }}
        - cmake
        - pkg-config
        - ninja
      host:
        - rocm-core ${{ version }}.*
        - rocm-cmake
        - sqlite
    tests:
      - package_contents:
          lib:
            - rocfft

  - package:
      name: librocfft-devel
    inherit:
      from: rocfft-build
      run_exports: false
    build:
      files:
        - include/**
        - lib/*.a
        - lib/cmake/**
        - lib/pkgconfig/**
        - share/pkgconfig/**
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('hip') }}
        - cmake
        - pkg-config
        - ninja
      host:
        - rocm-core ${{ version }}.*
        - rocm-cmake
        - sqlite

      run:
        - hip-devel
        - ${{ pin_subpackage('librocfft', exact=True) }}

      run_exports:
        - ${{ pin_subpackage('librocfft', upper_bound='x.x') }}
    tests:
      - requirements:
          run:
            - cmake-package-check
            - ${{ compiler('c') }}
            - ${{ compiler('cxx') }}
        script:
          - cmake-package-check rocfft
      - package_contents:
          include:
            - rocfft/rocfft.h

about:
  homepage: https://rocm.docs.amd.com/projects/rocFFT
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: "rocFFT library."

extra:
  recipe-maintainers:
    - traversaro
