context:
  name: hipfft
  version: "7.2.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/rocm-libraries/releases/download/rocm-${{ version }}/hipfft.tar.gz"
    sha256: 65d08232b0f83dda214c96e869db4b68380a12a7f6526ae008ec5faf19ec30e9

build:
  number: 0
  skip: 
    - not linux
    - hip_compiler_version in (None, "None")

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('hip') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - rocm-core ${{ version }}.*
    - rocm-cmake
    - rocfft
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  # Needs hip-devel
  #- requirements:
  #    run:
  #      - cmake-package-check
  #      - ${{ compiler('c') }}
  #      - ${{ compiler('cxx') }}
  #  script:
  #    - cmake-package-check hipfft
  - package_contents:
      include:
        - hipfft/hipfft.h
      lib:
        - hipfft

about:
  homepage: https://rocm.docs.amd.com/projects/hipFFT
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: "hipFFT is an FFT marshalling library."

extra:
  recipe-maintainers:
    - traversaro