schema_version: 1

context:
  name: rocblas
  version: "7.2.4"

recipe:
  name: rocblas-split
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/rocm-libraries/releases/download/rocm-${{ version }}/rocblas.tar.gz"
    sha256: fd909c8ee626be20641d1aad20eec5b1c4535d14d4ba6f488874df230a3b3b04
    target_directory: projects/rocblas
  - url: "https://github.com/ROCm/rocm-libraries/releases/download/rocm-${{ version }}/tensile.tar.gz"
    sha256: 3d31f46117a5d982d01032c2fed65eae5a3c26b33d496acb9cd19f60d107cce9
    target_directory: shared/tensile

build:
  number: 2
  skip: 
    - not linux
    - hip_compiler_version in (None, "None")

outputs:
  - staging:
      name: rocblas-build
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('hip') }}
        - cmake
        - pkg-config
        - ninja
        # Needed for tensilite
        - python ${{ python_min }}.*
        - pip
        - setuptools
        - msgpack-python
        - joblib
        - pyyaml
        - packaging
        - llvm-openmp
      host:
        - rocm-core ${{ version }}.*
        - rocm-cmake
        - rocm-smi
        - roctracer
        - libhipblas-common-devel
        - libhipblaslt-devel
        # Needed for tensilite
        - python ${{ python_min }}.*
        - pip
        - setuptools
        - msgpack-cxx
        - libboost-devel
        - msgpack-python
        - joblib
        - pyyaml
        - packaging
        - rocm-smi
      ignore_run_exports:
        # Ignoring as these are test-only dependencies
        from_package:
          - python
    build:
      script: build.sh

  - package:
      name: librocblas
    inherit:
      from: rocblas-build
      run_exports: false
    build:
      files:
        - bin/**
        - lib/librocblas.so*
        - lib/rocblas/**
        - share/doc/**
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('hip') }}
        - cmake
        - pkg-config
        - ninja
        # Needed for tensilite
        - python ${{ python_min }}.*
        - pip
        - setuptools
        - msgpack-python
        - joblib
        - pyyaml
        - packaging
        - llvm-openmp
      host:
        - rocm-core ${{ version }}.*
        - rocm-cmake
        - rocm-smi
        - roctracer
        - libhipblas-common-devel
        - libhipblaslt-devel
        # Needed for tensilite
        - python ${{ python_min }}.*
        - pip
        - setuptools
        - msgpack-cxx
        - libboost-devel
        - msgpack-python
        - joblib
        - pyyaml
        - packaging
        - rocm-smi
      ignore_run_exports:
        # Ignoring as these are test-only dependencies
        from_package:
          - python
    tests:
      - package_contents:
          lib:
            - rocblas

  - package:
      name: librocblas-devel
    inherit:
      from: rocblas-build
      run_exports: false
    build:
      files:
        - include/**
        - lib/*.a
        - lib/cmake/**
        - lib/pkgconfig/**
        - share/pkgconfig/**
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('hip') }}
        - cmake
        - pkg-config
        - ninja
        # Needed for tensilite
        - python ${{ python_min }}.*
        - pip
        - setuptools
        - msgpack-python
        - joblib
        - pyyaml
        - packaging
        - llvm-openmp
      host:
        - rocm-core ${{ version }}.*
        - rocm-cmake
        - rocm-smi
        - roctracer
        - libhipblas-common-devel
        - libhipblaslt-devel
        # Needed for tensilite
        - python ${{ python_min }}.*
        - pip
        - setuptools
        - msgpack-cxx
        - libboost-devel
        - msgpack-python
        - joblib
        - pyyaml
        - packaging
        - rocm-smi
      ignore_run_exports:
        # Ignoring as these are test-only dependencies
        from_package:
          - python

      run:
        - hip-devel
        - libhipblas-common-devel
        - libhipblaslt-devel
        - libboost-devel
        - ${{ pin_subpackage('librocblas', exact=True) }}

      run_exports:
        - ${{ pin_subpackage('librocblas', upper_bound='x.x') }}
    tests:
      - requirements:
          run:
            - cmake-package-check
            - ${{ compiler('c') }}
            - ${{ compiler('cxx') }}
        script:
          - cmake-package-check rocblas
      - package_contents:
          include:
            - rocblas/rocblas.h

about:
  homepage: https://rocm.docs.amd.com/projects/rocBLAS
  license: MIT
  license_family: MIT
  license_file: projects/rocblas/LICENSE.md
  summary: "rocBLAS is the AMD library for BLAS in ROCm. Implemented using the HIP language and optimized for AMD GPUs."

extra:
  recipe-maintainers:
    - traversaro
