{% set name = "rocm-comgr" %}
{% set version = "7.2.1" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ROCm/llvm-project/archive/refs/tags/rocm-{{ version }}.tar.gz
  sha256: 4d3449d758e3f79b336248b0207a394eda04ba5cdd48a4088e135ddf769127fa
  patches:
    - patches/rocm-comgr-7.2.0-llvm-22-compat.patch

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
  host:
    - clangdev 22.*
    - llvmdev 22.*
    - llvm
    - lld
    - zlib
    - zstd
    - rocm-core {{ version }}
    - rocm-device-libs  {{ version }}
    - rocm-cmake  {{ version }}

test:
  commands:
    - test -f $PREFIX/include/amd_comgr/amd_comgr.h
    - test -f $PREFIX/lib/libamd_comgr.so

about:
  home: https://github.com/ROCm/llvm-project/tree/amd-staging/amd/comgr
  license: NCSA
  license_file: amd/comgr/LICENSE.txt
  summary: 'ROCm Code Object Manager'

extra:
  recipe-maintainers:
    - zklaus
    - isuruf
