context:
  name: hipblaslt
  version: "7.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/rocm-libraries/releases/download/rocm-${{ version }}/hipblaslt.tar.gz"
    sha256: d6364248679857c489244d49d5e3c606ca24bace77dd6ad7be70bccdfabf8e1b
    target_directory: projects/hipblaslt
  - url: "https://github.com/ROCm/rocm-libraries/releases/download/rocm-${{ version }}/origami.tar.gz"
    sha256: e51552b3f1a88b55a2baf6e9bef42b610d6a792dfeedb1c65e13cd27a1a5aa97
    target_directory: shared/origami
  - url: "https://github.com/ROCm/rocm-libraries/releases/download/rocm-${{ version }}/mxdatagenerator.tar.gz"
    sha256: 2e10bc34b1f7eeacd0ac78dc84c602701f29e52d5e3fe233b88ec622a259f1f3
    target_directory: shared/mxdatagenerator
  - url: "https://github.com/ROCm/rocm-libraries/releases/download/rocm-${{ version }}/rocroller.tar.gz"
    sha256: 5a1c6e35b7c52a3a1fd2e2333efcc049788cd703ba145c6c9f020782bf40bd0d
    target_directory: shared/rocroller
    patches:
      - patches/rocroller-find-yaml-cpp.patch

build:
  number: 0
  skip: 
    - not linux
    - hip_compiler_version in (None, "None")

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('hip') }}
      # Test dependencies
    - ${{ compiler('fortran') }}
    # Workaround for rocroller bug, remove in the future
    - cmake<4
    - pkg-config
    - ninja
    # Needed for tensilite
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - msgpack-python
    - joblib
    - pyyaml
    - packaging
  host:
    - rocm-core ${{ version }}.*
    - rocm-cmake ${{ version }}.*
    - hipblas-common
    - roctracer
    # Needed for tensilite
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - msgpack-python
    - joblib
    - pyyaml
    - packaging
    - msgpack-cxx
    - libboost-devel
    - rocm-smi
    # rocroller depedencies
    - fmt
    - spdlog
    - yaml-cpp
    # Test dependencies
    - blis
    - liblapack
    - gtest
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}
  ignore_run_exports:
    # Ignoring as these are test-only dependencies
    from_package:
      - ${{ compiler('fortran') }}
      - blis
      - liblapack
      - gtest

tests:
  # Temporary commented out, find_package(hipblaslt) needs
  # hip-devel to be installed to work, but it does not make sense
  # to add that as a run dependency, unless we add a hipblaslt-devel
  # package.
  # - requirements:
  #    run:
  #      - cmake-package-check
  #      - ${{ compiler('c') }}
  #      - ${{ compiler('cxx') }}
  #  script:
  #    - cmake-package-check hipblaslt
  - package_contents:
      include:
        - hipblaslt/hipblaslt.h
      lib:
        - hipblaslt
about:
  homepage: https://rocm.docs.amd.com/projects/hipBLASLt
  repository: https://github.com/ROCm/rocm-libraries
  license: MIT
  license_family: MIT
  license_file: projects/hipblaslt/LICENSE.md
  summary: "HIP library for GEMM operations with extended functionality"

extra:
  recipe-maintainers:
    - traversaro
