context:
  name: rocm-core
  version: "7.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/rocm-systems/releases/download/rocm-${{ version }}/rocm-core.tar.gz"
    sha256: 372221919ca31accb1e6567acf21062d56b93b8df0c25ab3e7a9ab15c331578e

build:
  number: 0
  skip: not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  - requirements:
      run:
        - cmake-package-check
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
    script:
      - cmake-package-check rocm-core
  - package_contents:
      include:
        - rocm-core/rocm_version.h
      lib:
        - rocm-core

about:
  homepage: https://github.com/ROCm/rocm-core
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: "ROCm core package"

extra:
  recipe-maintainers:
    - traversaro
