{% set name = "rocr-runtime" %}
{% set version = "7.2.1" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ROCm/rocm-systems/releases/download/rocm-{{ version }}/rocr-runtime.tar.gz
  sha256: 0061a4926013f178fa2d66f09c08e65aea4f53a7643d8125751bda2a0e5aba00

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    # For xxd
    - vim
  host:
    - elfutils
    - rocm-device-libs {{ version }}
    - clangdev 22.*
    - llvmdev  22.*
    - lld      22.*
    - numactl
    - libdrm
    - zlib
    - rocm-core {{ version }}

test:
  commands:
    - test -f $PREFIX/include/hsa/hsa.h
    - test -f $PREFIX/lib/libhsa-runtime64.so

about:
  home: https://github.com/ROCm/ROCR-Runtime
  license: NCSA
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'ROCm Platform Runtime: ROCr a HPC market enhanced HSA based runtime'

extra:
  recipe-maintainers:
    - zklaus
    - isuruf
