context:
  name: rocrand
  version: "7.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/ROCm/rocm-libraries/releases/download/rocm-${{ version }}/rocrand.tar.gz
  sha256: c93a345c5b935fb16f947823dcbdcfaea57efcc98427d7f3bee57aa472c2cea8

build:
  number: 0
  skip:
    - not linux
    - hip_compiler_version in (None, "None")

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    # Workaround for https://github.com/conda-forge/ctng-compiler-activation-feedstock/issues/182
    - libstdcxx-devel_linux-64 >=15
    - libgcc-devel_linux-64 >=15.2.0
    - ${{ compiler('hip') }}
    - cmake
    - ninja
  host:
    - rocm-core ${{ version }}.*
    - rocm-cmake
  run_exports:
    - ${{ pin_subpackage(name, upper_bound="x.x") }}

tests:
  - package_contents:
      include:
        - rocrand/rocrand.h
        - rocrand/rocrand_xorwow.h
      lib:
        - librocrand${{ dso_ext }}

about:
  repository: https://github.com/ROCm/rocRAND
  license: MIT
  license_file: LICENSE.txt
  summary: "ROCm random number generation library"
  description: |
    rocRAND is a library for generating pseudo-random and quasi-random numbers
    on AMD GPUs using the ROCm platform. It provides implementations of various
    random number generators including XORWOW, MRG32K3A, MTGP32, Philox, and Sobol.

extra:
  recipe-maintainers:
    - flferretti
    - conda-forge/rocm-core
