schema_version: 1

context:
  name: rocwmma
  version: "7.2.4"

recipe:
  name: rocwmma-split
  version: ${{ version }}

source:
  url: https://github.com/ROCm/rocm-libraries/releases/download/rocm-${{ version }}/rocwmma.tar.gz
  sha256: 0d92dad3d7e8a16aa0aca9f09c018412630a81312cb0f8a3dae690aea9856049
  patches:
    - 0001-no-test-install.patch
    - 0002-relax-fp8-check.patch

build:
  number: 0
  skip:
    - not linux
    - hip_compiler_version in (None, "None")

outputs:
  - staging:
      name: rocwmma-build
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib("c") }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('hip') }}
        - cmake
        - ninja
      host:
        - rocm-core ${{ version }}.*
        - rocm-cmake
        - libgomp
    build:
      script: build.sh

  - package:
      name: librocwmma-devel
    inherit:
      from: rocwmma-build
      run_exports: false
    build:
      files:
        - include/**
        - lib/*.a
        - lib/cmake/**
        - lib/pkgconfig/**
        - share/pkgconfig/**
        - share/doc/**
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib("c") }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('hip') }}
        - cmake
        - ninja
      host:
        - rocm-core ${{ version }}.*
        - rocm-cmake
        - libgomp

      run:
        - hip-devel

      run_exports:
        - ${{ pin_subpackage('librocwmma-devel', upper_bound='x.x') }}
    tests:
      - package_contents:
          include:
            - rocwmma/rocwmma.hpp
          files:
            - lib/cmake/rocwmma/rocwmma-config.cmake

about:
  repository: https://github.com/ROCm/rocWMMA
  homepage: https://rocm.docs.amd.com/projects/rocWMMA/en/latest/
  license: MIT
  license_file: LICENSE.md
  summary: "AMD GPU C++ header-only library for GEMM primitives based on WMMA instructions"

extra:
  recipe-maintainers:
    - traversaro
