schema_version: 1

context:
  name: rocsolver
  version: "7.2.4"

recipe:
  name: rocsolver-split
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/rocm-libraries/releases/download/rocm-${{ version }}/rocsolver.tar.gz"
    sha256: 174ddf22656950984dea1768d9232df5278a81c747a6eb272670e80cfac262a7

build:
  number: 0
  skip: 
    - not linux
    - hip_compiler_version in (None, "None")

outputs:
  - staging:
      name: rocsolver-build
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('hip') }}
        - cmake
        - pkg-config
        - ninja
      host:
        - rocm-core ${{ version }}.*
        - rocm-cmake
        - librocblas-devel
        - librocprim-devel
    build:
      script: build.sh

  - package:
      name: librocsolver
    inherit:
      from: rocsolver-build
      run_exports: false
    build:
      files:
        - bin/**
        - lib/librocsolver.so*
        - share/doc/**
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('hip') }}
        - cmake
        - pkg-config
        - ninja
      host:
        - rocm-core ${{ version }}.*
        - rocm-cmake
        - librocblas-devel
        - librocprim-devel
    tests:
      - package_contents:
          lib:
            - ${{ name }}

  - package:
      name: librocsolver-devel
    inherit:
      from: rocsolver-build
      run_exports: false
    build:
      files:
        - include/**
        - lib/*.a
        - lib/cmake/**
        - lib/pkgconfig/**
        - share/pkgconfig/**
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('hip') }}
        - cmake
        - pkg-config
        - ninja
      host:
        - rocm-core ${{ version }}.*
        - rocm-cmake
        - librocblas-devel
        - librocprim-devel

      run:
        - hip-devel
        - librocblas-devel
        - librocprim-devel
        - ${{ pin_subpackage('librocsolver', exact=True) }}

      run_exports:
        - ${{ pin_subpackage('librocsolver', upper_bound='x.x') }}
    tests:
      - requirements:
          run:
            - cmake-package-check
            - ${{ compiler('c') }}
            - ${{ compiler('cxx') }}
        script:
          - cmake-package-check rocsolver
      - package_contents:
          include:
            - ${{ name }}/${{ name }}.h

about:
  homepage: https://rocm.docs.amd.com/projects/rocSOLVER
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: "AMD ROCm SOLVER library."

extra:
  recipe-maintainers:
    - traversaro
