context:
  name: rocsolver
  version: "7.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/rocm-libraries/releases/download/rocm-${{ version }}/rocsolver.tar.gz"
    sha256: d884fde0f6f55ceb46066b02496ed41ad75cd7e69e4846833a0fd320c162b9f8

build:
  number: 0
  skip: 
    - not linux
    - hip_compiler_version in (None, "None")

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - libgcc-devel_linux-64 >=15.2.0
    - ${{ compiler('hip') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - rocm-core ${{ version }}.*
    - rocm-cmake
    - rocblas
    - rocprim
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  # needs hip-devel
  #- requirements:
  #    run:
  #      - cmake-package-check
  #      - ${{ compiler('c') }}
  #      - ${{ compiler('cxx') }}
  #  script:
  #    - cmake-package-check ${{ name }}
  - package_contents:
      include:
        - ${{ name }}/${{ name }}.h
      lib:
        - ${{ name }}

about:
  homepage: https://rocm.docs.amd.com/projects/rocSOLVER
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: "AMD ROCm SOLVER library."

extra:
  recipe-maintainers:
    - traversaro