context:
  name: hipblas-common
  version: "7.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/rocm-libraries/releases/download/rocm-${{ version }}/hipblas-common.tar.gz"
    sha256: acb1e40f3a7f8013ce8b5c133af9c242dfbe251226562cf5f328b0184a867c46

build:
  number: 0
  skip: not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - libgcc-devel_linux-64 >=15.2.0
    - cmake
    - pkg-config
    - ninja
  host:
    - rocm-core ${{ version }}.*
    - rocm-cmake ${{ version }}.*


tests:
  - requirements:
      run:
        - cmake-package-check
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
    script:
      - cmake-package-check hipblas-common
  - package_contents:
      include:
        - hipblas-common/hipblas-common.h

about:
  homepage: https://github.com/ROCm/rocm-libraries
  repository: https://github.com/ROCm/rocm-libraries
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: "hipBLAS-common is a header-only library that provides common files for hipBLAS and hipBLASLt."

extra:
  recipe-maintainers:
    - traversaro