context:
  name: hiprand
  version: "7.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/ROCm/rocm-libraries/releases/download/rocm-${{ version }}/hiprand.tar.gz
  sha256: a9991655563c354511cb60594c884d12a22496fc05093f18373277224d951735

build:
  number: 0
  skip:
    - not linux
    - hip_compiler_version in (None, "None")

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('hip') }}
    - ${{ compiler('fortran') }}
    - cmake
    - ninja
  host:
    - rocm-core ${{ version }}.*
    - rocm-cmake
    - rocrand
  run_exports:
    - ${{ pin_subpackage(name, upper_bound="x.x") }}

tests:
  - package_contents:
      include:
        - hiprand/hiprand.h
      lib:
        - hiprand

about:
  repository: https://github.com/ROCm/hipRAND
  homepage: https://rocm.docs.amd.com/projects/hipRAND/en/latest/
  license: MIT
  license_file: LICENSE.txt
  summary: "ROCm RAND marshalling library"
  description: |
    hipRAND is a RAND marshalling library with multiple supported backends.
    It sits between your application and the backend RAND library, where it marshals
    inputs to the backend and results to the application.

extra:
  recipe-maintainers:
    - flferretti
    - conda-forge/rocm-core
