schema_version: 1

context:
  name: rocroller
  version: "7.2.4"

recipe:
  name: rocroller-split
  version: ${{ version }}

source:
  url: https://github.com/ROCm/rocm-libraries/releases/download/rocm-${{ version }}/rocroller.tar.gz
  sha256: d37e6e468d8a0add2056b947b94b09a96dd6fce665d4f8c3164a0117596b7403

build:
  number: 0
  skip:
    - not linux
    - hip_compiler_version in (None, "None")

outputs:
  - staging:
      name: rocroller-build
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('hip') }}
        - cmake<4
        - ninja
      host:
        - rocm-core ${{ version }}.*
        - rocm-cmake ${{ version }}.*
        - rocm-comgr ${{ version }}.*
        - fmt >=11.1.3
        - spdlog
        - yaml-cpp
        - libdivide
        - msgpack-cxx
        - libboost-devel
      ignore_run_exports:
        from_package:
          - libboost-devel
    build:
      script: build.sh

  - package:
      name: librocroller
    inherit:
      from: rocroller-build
      run_exports: false
    build:
      files:
        - lib/librocroller.so*
        - share/doc/**
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('hip') }}
        - cmake<4
        - ninja
      host:
        - rocm-core ${{ version }}.*
        - rocm-cmake ${{ version }}.*
        - rocm-comgr ${{ version }}.*
        - fmt >=11.1.3
        - spdlog
        - yaml-cpp
        - libdivide
        - msgpack-cxx
        - libboost-devel
      ignore_run_exports:
        from_package:
          - libboost-devel
      run:
        - rocm-comgr ${{ version }}.*
    tests:
      - package_contents:
          lib:
            - rocroller

  - package:
      name: librocroller-devel
    inherit:
      from: rocroller-build
      run_exports: false
    build:
      files:
        - include/**
        - lib/*.a
        - lib/cmake/**
        - lib/pkgconfig/**
        - share/pkgconfig/**
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('hip') }}
        - cmake<4
        - ninja
      host:
        - rocm-core ${{ version }}.*
        - rocm-cmake ${{ version }}.*
        - rocm-comgr ${{ version }}.*
        - fmt >=11.1.3
        - spdlog
        - yaml-cpp
        - libdivide
        - msgpack-cxx
        - libboost-devel
      ignore_run_exports:
        from_package:
          - libboost-devel

      run:
        - hip-devel
        - fmt >=11.1.3
        - yaml-cpp
        - ${{ pin_subpackage('librocroller', exact=True) }}

      run_exports:
        - ${{ pin_subpackage('librocroller', upper_bound='x.x') }}
    tests:
      - requirements:
          run:
            - cmake-package-check
            - ${{ compiler('c') }}
            - ${{ compiler('cxx') }}
        script:
          - cmake-package-check rocroller
      - package_contents:
          include:
            - rocRoller/Context.hpp

about:
  homepage: https://github.com/ROCm/rocm-libraries
  repository: https://github.com/ROCm/rocm-libraries
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: "A library for generating AMDGPU kernels"

extra:
  recipe-maintainers:
    - traversaro
