{% set name = "rocm-cmake" %}
{% set version = "7.2.1" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ROCm/rocm-cmake/archive/refs/tags/rocm-{{ version }}.tar.gz
  sha256: 5eec670557b41516e9e27738d20178122b5b536344f471ab823b308d3c767588

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    # Workaround for https://github.com/conda-forge/ctng-compiler-activation-feedstock/issues/182
    - libstdcxx-devel_linux-64 >=15  # [linux]
    - cmake
    - make
  host:
    - rocm-core {{ version }}
  run:

test:
  commands:
    - test -f $PREFIX/share/rocm/cmake/ROCMConfig.cmake

about:
  home: https://github.com/ROCm/rocm-cmake
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Rocm cmake modules'

extra:
  recipe-maintainers:
    - isuruf