context:
  name: hipblas
  version: "7.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/rocm-libraries/releases/download/rocm-${{ version }}/hipblas.tar.gz"
    sha256: 4b520aa568e02eecabf6c5503adc6e5a3f2a6b32cb4be8c21aebffc48f85a8e6

build:
  number: 0
  skip: 
    - not linux
    - hip_compiler_version in (None, "None")

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - libgcc-devel_linux-64 >=15.2.0
    - ${{ compiler('hip') }}
    # Note: fortran is only required on Linux
    - ${{ compiler('fortran') }}
    - cmake
    - pkg-config
    - ninja
    # Needed by rocm_check_target_ids CMake function
    - lld 20.*
  host:
    - rocm-core ${{ version }}.*
    - rocm-cmake
    - rocm-smi
    - hipblaslt
    - roctracer
    - hipblas-common
    - rocblas
    - rocsolver
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  # Needs hip-devel
  #- requirements:
  #    run:
  #      - cmake-package-check
  #      - ${{ compiler('c') }}
  #      - ${{ compiler('cxx') }}
  #  script:
  #    - cmake-package-check hipblas
  - package_contents:
      include:
        - hipblas/hipblas.h
      lib:
        - hipblas

about:
  homepage: https://rocm.docs.amd.com/projects/hipBLAS
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: "ROCm BLAS marshalling library."

extra:
  recipe-maintainers:
    - traversaro