[workspace]
authors = ["Silvio Traversaro <silvio@traversaro.it>"]
channels = ["https://prefix.dev/rock-the-conda-strix", "https://prefix.dev/conda-forge"]
name = "llama.cpp"
platforms = ["linux-64"]

# Run:
# pixi run benchmark to run llama-bench on a simple llm model with rocm, and
# pixi run -e vulkan benchmark to run the same benchmark with vulkan

[dependencies]
"llama.cpp" = { version = "*", build = "*rocm*" }
curl = "*"

# The cpu build of llama.cpp actually has vulkan support
[feature.vulkan.dependencies]
"llama.cpp" = { version = "*", build = "*cpu*" }
curl = "*"

[feature.tasks.tasks]
download_model = { cmd = "curl -L -o gemma-3-1b-it-Q4_K_M.gguf https://huggingface.co/ggml-org/gemma-3-1b-it-GGUF/resolve/main/gemma-3-1b-it-Q4_K_M.gguf", outputs = [
  "gemma-3-1b-it-Q4_K_M.gguf",
] }
benchmark = {cmd="llama-bench -m ./gemma-3-1b-it-Q4_K_M.gguf", depends-on="download_model"}


[environments]
default = { features = ["tasks"] }
vulkan = { features = ["vulkan", "tasks"], no-default-feature = true }
