context:
  name: rocprim
  version: "7.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/rocm-libraries/releases/download/rocm-${{ version }}/rocprim.tar.gz"
    sha256: a6d1a6a2bf829ea74741364a2d65409eed718249a4f54f1c1cf639785217d626

build:
  number: 0
  skip: 
    - not linux
    - hip_compiler_version in (None, "None")

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('hip') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - rocm-core ${{ version }}.*
    - rocm-cmake


tests:
  # Temporary commented out, find_package(rocprim) needs
  # hip-devel to be installed to work, but it does not make sense
  # to add that as a run dependency, unless we add a rocprim-devel
  # package.
  # - requirements:
  #    run:
  #      - cmake-package-check
  #      - ${{ compiler('c') }}
  #      - ${{ compiler('cxx') }}
  #  script:
  #    - cmake-package-check rocprim
  - package_contents:
      include:
        - ${{ name }}/${{ name }}.hpp

about:
  homepage: https://rocm.docs.amd.com/projects/rocPRIM
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "rocPRIM is a header-only library that provides HIP parallel primitives."

extra:
  recipe-maintainers:
    - traversaro