context:
  version: "7.2.1"

package:
  name: aqlprofile
  version: ${{ version }}

source:
  url: https://github.com/ROCm/rocm-systems/releases/download/rocm-${{ version }}/aqlprofile.tar.gz
  sha256: 1e3801517826b92a9c114edece6a1e098a14902c0b87298c0f18c03de90aac73

build:
  number: 0
  skip:
    - not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - libgcc-devel_linux-64 >=15.2.0
    - cmake
    - ninja
  host:
    - rocm-core
    - rocr-runtime

about:
  homepage: https://github.com/ROCm/aqlprofile
  license: MIT
  license_file: LICENSE
  summary: AQLPROFILE library for AMD GPU profiling
  description: |
    AQLPROFILE provides AQL packet level profiling support for AMD GPUs.
    It is used by profiling tools to collect hardware performance counters.

extra:
  recipe-maintainers:
    - flferretti
    - conda-forge/rocm-core
