schema_version: 1

context:
  name: hipsparse
  version: "7.2.4"

recipe:
  name: hipsparse-split
  version: ${{ version }}

source:
  url: https://github.com/ROCm/rocm-libraries/releases/download/rocm-${{ version }}/hipsparse.tar.gz
  sha256: a1a1212746e4605703a3b42644bad83b07f6e7369d651dd657cd35611504a57a

build:
  number: 0
  skip:
    - not linux
    - hip_compiler_version in (None, "None")

outputs:
  - staging:
      name: hipsparse-build
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib("c") }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('hip') }}
        - ${{ compiler('fortran') }}
        - cmake
        - ninja
      host:
        - rocm-core ${{ version }}.*
        - rocm-cmake
        - librocsparse-devel
    build:
      script: build.sh

  - package:
      name: libhipsparse
    inherit:
      from: hipsparse-build
      run_exports: false
    build:
      files:
        - bin/**
        - lib/libhipsparse.so*
        - share/doc/**
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib("c") }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('hip') }}
        - ${{ compiler('fortran') }}
        - cmake
        - ninja
      host:
        - rocm-core ${{ version }}.*
        - rocm-cmake
        - librocsparse-devel
    tests:
      - package_contents:
          lib:
            - hipsparse

  - package:
      name: libhipsparse-devel
    inherit:
      from: hipsparse-build
      run_exports: false
    build:
      files:
        - include/**
        - lib/*.a
        - lib/cmake/**
        - lib/pkgconfig/**
        - share/pkgconfig/**
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib("c") }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('hip') }}
        - ${{ compiler('fortran') }}
        - cmake
        - ninja
      host:
        - rocm-core ${{ version }}.*
        - rocm-cmake
        - librocsparse-devel

      run:
        - hip-devel
        - librocsparse-devel
        - ${{ pin_subpackage('libhipsparse', exact=True) }}

      run_exports:
        - ${{ pin_subpackage('libhipsparse', upper_bound='x.x') }}
    tests:
      - package_contents:
          include:
            - hipsparse/hipsparse.h

about:
  repository: https://github.com/ROCm/hipSPARSE
  homepage: https://rocm.docs.amd.com/projects/hipSPARSE/en/latest/
  license: MIT
  license_file: LICENSE.md
  summary: "ROCm SPARSE marshalling library"
  description: |
    hipSPARSE is a SPARSE marshalling library with multiple supported backends.
    It sits between your application and a 'worker' SPARSE library, where it marshals
    inputs to the backend library and marshals results to the application.

extra:
  recipe-maintainers:
    - flferretti
    - conda-forge/rocm-core
