context:
  name: composable-kernel
  version: "7.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/ROCm/rocm-libraries/releases/download/rocm-${{ version }}/composablekernel.tar.gz
  sha256: b5a699f1bce24727ed333aeed8afd10a8ac3c1ddcf86eb86ec9d638a22c24125

build:
  number: 0
  skip:
    - not linux
    - hip_compiler_version in (None, "None")

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - libgcc-devel_linux-64 >=15.2.0
    - ${{ compiler('hip') }}
    - cmake
    - ninja
  host:
    - rocm-core ${{ version }}.*
    - rocm-cmake
  run_exports:
    - ${{ pin_subpackage(name, upper_bound="x.x") }}

tests:
  - package_contents:
      include:
        - ck/library/reference_tensor_operation/cpu/reference_gemm.hpp
        - ck/library/reference_tensor_operation/gpu/reference_gemm.hpp
        - ck/library/tensor_operation_instance/gpu/grouped_gemm.hpp
      lib:
        - device_conv_operations

about:
  repository: https://github.com/ROCm/composable_kernel
  license: MIT
  license_file: LICENSE
  summary: "Composable Kernel: Performance Portable Programming Model for Machine Learning Tensor Operators"
  description: |
    The Composable Kernel (CK) library provides a programming model for writing
    performance-critical kernels for machine learning workloads across multiple
    architectures (GPUs, CPUs, etc.).

extra:
  recipe-maintainers:
    - flferretti
    - conda-forge/rocm-core
