{% set name = "rocm-smi" %}
{% set version = "7.2.1" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ROCm/rocm-systems/releases/download/rocm-{{ version }}/rocm-smi-lib.tar.gz
  sha256: 5696259c01573e6e3961dfb781bbdb7a78a1ebab8614c66c18b6b71bdf6ee348

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - make
  host:
    - libdrm
    - rocm-core {{ version }}
  run:

test:
  commands:
    - test -f $PREFIX/bin/rocm-smi
    - test -f $PREFIX/lib/librocm_smi64$SHLIB_EXT.*.*  # [unix]
    - test -f $PREFIX/lib/liboam$SHLIB_EXT.*.*  # [unix]

about:
  home: https://github.com/RadeonOpenCompute/rocm_smi_lib
  summary: 'ROC System Management Interface'
  description: |
    The ROCm System Management Interface Library, or ROCm SMI library, is
    part of the Radeon Open Compute ROCm software stack . It is a C library
    for Linux that provides a user space interface for applications to 
    monitor and control GPU applications. In addition, this package includes 
    the rocm-smi tool. This tool exposes functionality for clock and 
    temperature management of your ROCm enabled system.
  license: NCSA
  license_family: OTHER
  license_file: LICENSE.md
  doc_url: https://github.com/RadeonOpenCompute/rocm_smi_lib
  dev_url: https://github.com/RadeonOpenCompute/rocm_smi_lib

extra:
  recipe-maintainers:
    - isuruf
    - jan-janssen
