schema_version: 1

context:
  name: hipsolver
  version: "7.2.4"

recipe:
  name: hipsolver-split
  version: ${{ version }}

source:
  url: https://github.com/ROCm/rocm-libraries/releases/download/rocm-${{ version }}/hipsolver.tar.gz
  sha256: 7f99c576b3fd5e6a379e285531dc68ade121918f6d41209ce534d857f421ff39

build:
  number: 0
  skip:
    - not linux
    - hip_compiler_version in (None, "None")

outputs:
  - staging:
      name: hipsolver-build
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib("c") }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('hip') }}
        - ${{ compiler('fortran') }}
        - cmake
        - ninja
      host:
        - rocm-core ${{ version }}.*
        - rocm-cmake
        - librocsolver-devel
        - librocblas-devel
    build:
      script: build.sh

  - package:
      name: libhipsolver
    inherit:
      from: hipsolver-build
      run_exports: false
    build:
      files:
        - lib/libhipsolver.so*
        - share/doc/**
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib("c") }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('hip') }}
        - ${{ compiler('fortran') }}
        - cmake
        - ninja
      host:
        - rocm-core ${{ version }}.*
        - rocm-cmake
        - librocsolver-devel
        - librocblas-devel
    tests:
      - package_contents:
          lib:
            - hipsolver

  - package:
      name: libhipsolver-devel
    inherit:
      from: hipsolver-build
      run_exports: false
    build:
      files:
        - include/**
        - lib/*.a
        - lib/cmake/**
        - lib/pkgconfig/**
        - share/pkgconfig/**
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib("c") }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('hip') }}
        - ${{ compiler('fortran') }}
        - cmake
        - ninja
      host:
        - rocm-core ${{ version }}.*
        - rocm-cmake
        - librocsolver-devel
        - librocblas-devel

      run:
        - hip-devel
        - librocsolver-devel
        - librocblas-devel
        - ${{ pin_subpackage('libhipsolver', exact=True) }}

      run_exports:
        - ${{ pin_subpackage('libhipsolver', upper_bound='x.x') }}
    tests:
      - package_contents:
          include:
            - hipsolver/hipsolver.h

about:
  repository: https://github.com/ROCm/hipSOLVER
  homepage: https://rocm.docs.amd.com/projects/hipSOLVER/en/latest/
  license: MIT
  license_file: LICENSE.md
  summary: "ROCm LAPACK marshalling library"
  description: |
    hipSOLVER is a LAPACK marshalling library with multiple supported backends.
    It sits between your application and a 'worker' LAPACK library, where it marshals
    inputs to the backend library and marshals results to the application.

extra:
  recipe-maintainers:
    - flferretti
    - conda-forge/rocm-core
