context:
  name: hipsolver
  version: "7.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/ROCm/rocm-libraries/releases/download/rocm-${{ version }}/hipsolver.tar.gz
  sha256: 8f56b56b3523065ac8edf334a5789b5cf32ace7a1b616fd0826e5d11d57287a1

build:
  number: 0
  skip:
    - not linux
    - hip_compiler_version in (None, "None")

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - libgcc-devel_linux-64 >=15.2.0
    - ${{ compiler('hip') }}
    - ${{ compiler('fortran') }}
    - cmake
    - ninja
  host:
    - rocm-core ${{ version }}.*
    - rocm-cmake
    - rocsolver
    - rocblas
  run_exports:
    - ${{ pin_subpackage(name, upper_bound="x.x") }}

tests:
  - package_contents:
      include:
        - hipsolver/hipsolver.h
      lib:
        - hipsolver

about:
  repository: https://github.com/ROCm/hipSOLVER
  homepage: https://rocm.docs.amd.com/projects/hipSOLVER/en/latest/
  license: MIT
  license_file: LICENSE.md
  summary: "ROCm LAPACK marshalling library"
  description: |
    hipSOLVER is a LAPACK marshalling library with multiple supported backends.
    It sits between your application and a 'worker' LAPACK library, where it marshals
    inputs to the backend library and marshals results to the application.

extra:
  recipe-maintainers:
    - flferretti
    - conda-forge/rocm-core
