context:
  name: rocthrust
  version: "7.2.4"


package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/ROCm/rocm-libraries/releases/download/rocm-${{ version }}/rocthrust.tar.gz
  sha256: 13bf12e70f703144cbc9bb1c384b51e894f1c4fcbc5ea595cd6f235f8aa8f333

build:
  number: 0
  skip:
    - not linux
    - hip_compiler_version in (None, "None")

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('hip') }}
    - cmake
    - ninja
  host:
    - rocm-core ${{ version }}.*
    - rocm-cmake
    - rocprim ${{ version }}.*
  run_exports:
    - ${{ pin_subpackage(name, upper_bound="x.x") }}

tests:
  - package_contents:
      include:
        - thrust/version.h
        - thrust/rocthrust_version.hpp
      files:
        - lib/cmake/rocthrust/rocthrust-config.cmake

about:
  homepage: https://rocm.docs.amd.com/projects/rocThrust
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "ROCm parallel algorithm library, HIP back-end for Thrust."

extra:
  recipe-maintainers:
    - flferretti
    - conda-forge/rocm-core
