name: Build conda packages

on:
  workflow_dispatch:
  pull_request:

env:
  # Change to 'true' to ignore cache and force a full rebuild, but please restore to 'false' before merging
  IGNORE_CACHE_AND_DO_FULL_REBUILD: 'true'

jobs:
  build-packages:
    name: '[pixi:build-packages:${{ matrix.job_name }}]'
    runs-on: ${{ matrix.runs_on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - job_name: 'build-strix-packages'
            runs_on: [self-hosted, linux, x64, amdgpu]
            folder_cache: 'output/linux-64'
            target_channel: https://prefix.dev/rock-the-conda-strix

    steps:
    - uses: actions/checkout@v6

    - name: Set up pixi
      uses: prefix-dev/setup-pixi@v0.9.0

    - name: Print pixi info
      run: pixi info

    - name: Install global ccache and sccache
      shell: bash
      run: |
        pixi global install ccache sccache

    # ccache is used for caching of C and C++ compilation units
    - uses: Chocobo1/setup-ccache-action@v1
      with:
        install_ccache: false
        update_packager_index: false

    # sccache is used for caching of HIP compilation units
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.9

    # this is the cache of conda packages
    - name: Restore build cache
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          ${{ matrix.folder_cache }}
        key: ${{ matrix.job_name }}-conda-pkgs-cache
        # allow a later run to pick up a cache that has an extra suffix
        restore-keys: |
          ${{ matrix.job_name }}-conda-pkgs-cache

    - name: Optional force full rebuild
      if: ${{ env.IGNORE_CACHE_AND_DO_FULL_REBUILD == 'true' }}
      shell: bash -l {0}
      run: |
        rm -rf ${{ matrix.folder_cache }}/*

    - name: Patch HIP GPU targets for strix build
      if: ${{ matrix.job_name == 'build-strix-packages' }}
      shell: bash
      run: |
        sed -i 's|^export CONDA_FORGE_DEFAULT_ROCM_GPU_TARGETS=.*$|export CONDA_FORGE_DEFAULT_ROCM_GPU_TARGETS="gfx1150;gfx1151"|' recipes/hip/activate/hip-clang_activate.sh
        grep '^export CONDA_FORGE_DEFAULT_ROCM_GPU_TARGETS=' recipes/hip/activate/hip-clang_activate.sh

    - name: Build packages
      run: pixi run build-packages

    - name: Save build cache
      uses: actions/cache/save@v4
      if: always()
      with:
        path: |
          ${{ matrix.folder_cache }}
        key: ${{ matrix.job_name }}-conda-pkgs-cache-${{ github.run_id }}-${{ github.run_attempt }}
